
name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: build
      run: swift build -v
